window.FlowGridChangelog = [
  {
    date: "2026-04-28",
    commit: "7f3c479",
    title: "Core estatico inicial",
    changes: [
      "App estatica preparada para GitHub Pages con navegacion por modulos.",
      "Core de movimientos con alta, listado, filtros, resumen y persistencia local.",
      "Panel de configuracion para conceptos y categorias, con edicion inline.",
      "Modulo Novedades conectado a changelog.js.",
      "Criterios globales de fecha en es-ES, formato DD/MM/AAAA y hora 24h.",
      "Selector de fecha propio con semanas empezando en lunes.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "main@HEAD",
    title: "Densidad y ajustes visuales",
    changes: [
      "Escala general reducida para aprovechar mejor el espacio disponible.",
      "Listado de movimientos convertido a filas tabulares de una sola linea.",
      "Corregida la alineacion entre cabeceras y contenido de movimientos.",
      "Columnas de movimientos reordenadas y acciones de editar/eliminar separadas.",
      "El borrado de movimientos solicita confirmacion.",
      "Iconos sustituidos por SVGs minimalistas inline.",
      "Paneles centrados en escritorio dentro del espacio disponible.",
      "Configuracion reorganizada en conceptos/categorias, importacion CSV y backup JS.",
      "Importacion CSV con previsualizacion y backup JS exportable/importable.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "dev@HEAD",
    title: "Analisis temporal y gastos compartidos",
    changes: [
      "Resumen retirado de Movimientos y creados modulos Mes a mes y Año a Año con desglose por concepto/categoria.",
      "Navegacion separada por bloques y primer modulo Compartidos aislado de movimientos/configuracion.",
      "Home reorganizado en grupos Dineritos/Sistema y separador lateral tras Home en la barra superior.",
      "Alta de movimientos movida a modal responsive y categoria derivada automaticamente del concepto.",
      "Bloque Gasto compartido en el formulario: con quien y parte que debe, solo activable en gastos.",
      "Los gastos compartidos generan deudas con estado pendiente/satisfecha visibles en Compartidos.",
      "Anadida columna Compartido en el listado de movimientos para identificar gastos con deuda asociada.",
      "Borrado directo de deudas desde Compartidos con confirmacion.",
      "Limpieza automatica de deudas compartidas al borrar el movimiento que las origina.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "dev@HEAD",
    title: "Tarjetas en movil y duplicar movimientos",
    changes: [
      "Home: retirados los titulos Dineritos/Sistema, sustituidos por una linea sutil entre grupos.",
      "Movimientos en movil renderizados como tarjetas agrupadas por fecha, manteniendo la fila tabular en escritorio.",
      "Cada tarjeta muestra concepto y nota arriba a la izquierda, importe centrado, recurrencia arriba a la derecha y compartido abajo a la izquierda.",
      "Nuevo boton Copiar en cada movimiento que abre el modal pre-rellenado para crear entradas similares.",
      "Calendario del selector de fecha por encima del modal (antes quedaba detras y era inusable).",
      "Cruz de cerrar el modal reposicionada en la esquina superior derecha del dialogo.",
      "Eliminado el placeholder Sin nota cuando un movimiento no tiene nota.",
    ],
  },
];
