window.FlowGridChangelog = [
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Compartidos móvil: resumen tappable + tarjeta plana + ocultar Ver entradas",
    changes: [
      "En móvil, cuando el desplegable está en \"Todos\", el panel Saldos muestra un mini resumen tappable con cada colaborador en una línea: nombre, dirección (te debe / le debes / saldado) e importe en color. Tocar una fila equivale a seleccionar ese contacto en el desplegable — el resumen se sustituye por la tarjeta detallada y los movimientos compartidos abajo se filtran al instante. Responde a \"¿con quién debo o me deben?\" sin tener que abrir cada uno.",
      "Tarjeta de saldo del colaborador en móvil aplanada a 2 filas: nombre + etiqueta arriba a la izquierda, importe grande arriba a la derecha; el botón Liquidar saldo abajo. Antes el card era casi cuadrado y ocupaba media pantalla.",
      "Botón \"Ver entradas\" oculto en móvil — el desplegable del Saldos ya filtra los movimientos compartidos justo debajo, así que pulsarlo solo hubiera scrolleado a algo ya visible. Liquidar saldo queda solo en su fila.",
      "Empty-state \"Selecciona un contacto…\" pasa a banner horizontal compacto en lugar de un cuadro alto con padding generoso.",
    ],
  },
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Compartidos en móvil: selector de contacto y arreglos de historial",
    changes: [
      "En móvil, el panel \"Saldos\" muestra ahora solo la tarjeta del contacto seleccionado en un nuevo desplegable arriba del panel. Antes se apilaban todas las tarjetas y ocupaban toda la pantalla, dejando los movimientos fuera de vista. En desktop la rejilla con todas las tarjetas sigue intacta.",
      "Cuando el desplegable está en \"Todos\" en móvil, aparece un mensaje guía pidiendo que selecciones un contacto. Cualquier cambio en este desplegable también filtra la lista de movimientos compartidos justo debajo (un solo control para los dos paneles).",
      "Historial de cambios ahora muestra TAMBIÉN la última edición que acabas de hacer. Antes había una carrera entre el guardado del cambio y la grabación del log: el formulario se cerraba antes de que la línea de log llegara al cloud, así que al abrir el reloj inmediatamente después se veía un historial \"con un cambio de retraso\". Ahora el formulario espera a que la línea de log esté guardada antes de cerrarse.",
    ],
  },
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Compartidos paso 3: invitaciones, edición simétrica y registro de cambios",
    changes: [
      "Invitar a un contacto: en Configuración → Contactos cualquier contacto con email muestra un botón \"Invitar\". Al pulsarlo se manda un magic-link al email del contacto vía Resend. Cuando acepta, ambos lados ven los gastos compartidos comunes; tu UI muestra una etiqueta verde \"Vinculado\" donde antes estaba el botón.",
      "Recíproco automático: al aceptar la invitación, FlowGrid crea en la cuenta del invitado un contacto que apunta al inviter (con su email pre-rellenado), para que ambos lados puedan registrar nuevos gastos en común desde el principio.",
      "Edición simétrica: ahora puedes editar gastos compartidos del otro usuario directamente desde la lista de Compartidos. El formulario se abre con tu perspectiva (quién pagó, tu parte) y al guardar se aplica la inversión inversa para que el otro lado siga viéndolo coherente. El selector de contacto queda bloqueado al editar entradas del partner.",
      "Registro de cambios por entrada: un icono de reloj en cada fila abre un modal con el historial completo (quién, cuándo, qué cambió y comentario opcional). El registro es permanente: nada se borra ni se modifica. Útil para auditar cambios entre cuentas vinculadas.",
      "Liquidación por gasto concreto: además del \"Liquidar saldo\" global, ahora puedes marcar un gasto individual como liquidado con un botón en su fila. La entrada se atenúa, el importe se tacha y deja de contar al saldo. Reversible con un click (\"Reabrir\").",
      "Categoría \"Definir\" amarilla: cuando un gasto compartido del partner usa un concepto que no tienes catalogado, FlowGrid lo añade a tu lista con esta categoría de aviso. Tú decides en Configuración a qué categoría real lo asignas, sin afectar al otro usuario.",
      "Movimientos virtuales: la parte del partner se ve también como movimiento en tu lista personal y cuenta en tu análisis (Mes a mes, Año a año), aunque no hayas pagado el cash todavía. Lo que asumes es gasto tuyo igualmente; liquidar solo cierra el saldo en Compartidos, no añade ni quita movimientos.",
      "Tildes pulidas: \"Tu pagaste\" → \"Tú pagaste\", \"Contacto pago\" → \"Contacto pagó\", y orden de palabras correcto en el resumen de cada gasto compartido.",
    ],
  },
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Movimientos en móvil: card expandible al tocar y filtro inline congelado",
    changes: [
      "Card móvil simplificada: por defecto solo se ve concepto + importe + (badges de recurrencia y compartido si aplican). Al tocar la card, crece orgánicamente abajo con todos los datos del movimiento: fecha, categoría, recurrencia completa, emisor/receptor, nota, gasto compartido si aplica, y botones de acción (Editar / Duplicar / Eliminar).",
      "Filtro inline en lugar de modal. En móvil, \"Filtrar\" expande la cabecera con un selector de campo (Todos / Concepto / Nota / Emisor) y un input de búsqueda. En desktop, la barra de filtros es permanente con dropdowns combinables para Concepto, Categoría, Tipo + un input de texto que busca en TODOS los campos a la vez (concepto, nota, emisor, categoría, tipo, recurrencia y contacto compartido).",
      "Cabeceras congeladas al hacer scroll en desktop: la barra de filtro, los títulos de columnas (sortables) y el separador del mes que estás viendo. Al cruzar al siguiente mes, su separador empuja al anterior fuera de vista.",
      "Live-filter al teclear con debounce de 140ms para que la lista no se recalcule en cada pulsación cuando tienes mil movimientos.",
      "Botón de cerrar filtro reposicionado: en móvil va al lado del botón \"Filtrar\" (la fila del filtro queda en una sola línea), en desktop sigue dentro de la barra de filtros.",
    ],
  },
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Home con jerarquía visual + sidebar reorganizado + iconos PWA",
    changes: [
      "Las cuatro tarjetas principales del Home (Movimientos, Compartidos, Mes a mes, Año a año) tienen ahora un cuadradito de color detrás del icono — azul, violeta, verde, ámbar — con un tinte suave de fondo. Configuración, Novedades y Próximas mejoras pasan a una fila inferior compacta de \"links secundarios\" con menos peso visual.",
      "En móvil, los links secundarios aparecen solo como iconos (sin texto) para no apretar la pantalla.",
      "Sidebar y barra inferior móvil reordenadas en el mismo orden que las tarjetas (Movimientos · Compartidos · Mes a mes · Año a año). Botón de salir de sesión movido al rincón inferior. El email del usuario aparece a su lado como un chivato (texto, no botón).",
      "FlowGrid tiene icono propio en la pestaña del navegador y en \"Añadir a pantalla de inicio\" en iOS, Android, y al instalarla como app en cualquier sistema operativo. Color de tema verde teal coherente con el resto de la app.",
      "Build label arriba a la derecha incluye segundos (formato YYYY-MM-DD HH:mm:ss) para que sea trivial saber si tienes la última versión cacheada o una propagación pendiente.",
    ],
  },
  {
    date: "2026-05-02",
    commit: "dev@HEAD",
    title: "Botón de feedback operativo",
    changes: [
      "El formulario de \"¿Tienes una idea o detectas un fallo?\" en la vista Próximas mejoras ya envía mensajes de verdad. El correo llega con el remitente noreply@arcdev.app (mismo SMTP de Resend que los magic-links) y reply-to apuntando al email del usuario, para poder contestarle directamente.",
      "Estado live: \"Enviando…\" / \"¡Gracias! Tu feedback ha llegado bien.\" / mensaje de error si algo va mal.",
      "Backend: Edge Function en Supabase verificando el JWT del usuario y reenviando vía Resend.",
    ],
  },
  {
    date: "2026-05-01",
    commit: "dev@HEAD",
    title: "Exportar a CSV, onboarding en Compartidos y formulario de feedback",
    changes: [
      "Configuracion → CSV: nuevo boton \"Descargar CSV\" que exporta todos los movimientos con cabeceras en espanol (Fecha, Concepto, Importe, Tipo, Categoria, Emisor/Receptor, Recurrencia, Nota). Delimiter ; y BOM UTF-8 para que Excel ES, Numbers y Google Sheets lo abran sin tocar nada. Boton de info con tooltip al hover (escritorio) o tap (movil) que explica que incluye el archivo.",
      "Compartidos: panel introductorio arriba que explica el modelo (estilo Splitwise pero integrado con tu lista de gastos) con un ejemplo concreto. Plegable: aparece abierto la primera vez y se puede minimizar; FlowGrid recuerda tu eleccion entre sesiones.",
      "Nueva vista \"Proximas mejoras\" en sidebar y home: roadmap publico con lo que viene (compartidos en grupo, recurrencias automaticas, presupuestos, graficas, invitaciones a contactos).",
      "Formulario de feedback al final de \"Proximas mejoras\" como vista previa (atenuado, no operativo todavia). Cuando se active, mandara el mensaje directamente desde la app sin abrir cliente de correo. Mientras tanto, banner con email directo de contacto para casos urgentes.",
      "Tab \"Importar CSV\" pasa a llamarse simplemente \"CSV\" porque ahora alberga import y export.",
    ],
  },
  {
    date: "2026-05-01",
    commit: "29281ea",
    title: "SMTP propio con Resend + dominio arcdev.app",
    changes: [
      "FlowGrid envia los magic-links desde noreply@arcdev.app via Resend, con plantilla en espanol. Adios al rate limit de 3/h del relay default de Supabase.",
      "DNS de arcdev.app gestionado en Cloudflare con DKIM, SPF, DMARC (modo monitor) y MX para bounces.",
      "Rate limit de Supabase subido a 30 emails/hora; Resend free tier da 100 emails/dia, suficiente para los testers iniciales.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "dev@HEAD",
    title: "Rediseno mobile del modal de nuevo movimiento",
    changes: [
      "Tipo de movimiento como par de botones grandes (Gasto / Ingreso) en lugar de un select. Estado activo con tinte rojo (gasto) o verde (ingreso). Solo en mobile; el desktop sigue usando el select original.",
      "Reordenacion mobile: Tipo arriba, luego Fecha + Importe en grande (date-trigger 56px, importe 64px centrado y peso 700), Concepto, Recurrencia, Emisor, Nota, Compartido.",
      "Concepto por defecto en movimientos nuevos pasa a 'Compra' (si existe en la lista del usuario) en lugar de la primera entrada alfabetica. La recurrencia 'Puntual' ya era el default por estructura del select.",
      "Desktop intacto: todo el rediseno vive dentro del media query max-width: 719px.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "c0792b3",
    title: "Zona peligrosa: borrar todos los movimientos con doble confirmacion",
    changes: [
      "Nueva seccion al final de la pestana Backup con un boton para borrar todos los movimientos de golpe (local + cloud).",
      "Doble verificacion: hay que escribir literalmente BORRAR en mayusculas y luego confirmar de nuevo. Si el primer texto no coincide exacto, no pasa nada.",
      "Boton estilizado como destructivo (rojo ghost) y con copia clara del riesgo. No toca contactos, settings ni shared_entries.",
      "Limit explicito en queries: limit=50000 en cada GET para evitar la truncacion silenciosa a 1000 filas que tiene Supabase por defecto. Necesario para soportar varios anos de datos.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "95e0838",
    title: "Fase 3 — paso 2: campo email opcional en contactos",
    changes: [
      "Formulario de Contactos en Configuracion ahora pide tambien email (opcional). El campo se guarda y se sincroniza al cloud como cualquier otro dato del contacto.",
      "Edicion inline en la lista de contactos amplia la fila con un input de email junto al nombre. Ambos editables a la vez, se guardan con el mismo OK.",
      "Sin cambios funcionales todavia; el email queda preparado para el siguiente paso (envio de invitacion via magic-link).",
      "Limpieza: retirados los console.log diagnosticos del bypass de supabase-js que se quedaron en cloud.js y supabase.js tras resolver el bug de queries.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "adafce5",
    title: "Bypass de supabase-js para queries: fetch directo al endpoint REST",
    changes: [
      "Las queries de supabase-js se quedaban colgadas indefinidamente en Phase 3 sin error, sin trafico, sin timeout. Ni el override de `lock` a no-op, ni cachear la sesion, ni pinear v2.45.0 lo arreglaron — la cola interna pendingInLock del auth-client estaba rota.",
      "Reescrito core/cloud.js con fetch directo a /rest/v1/* usando el access_token cacheado desde onAuthStateChange. supabase-js sigue gestionando login/logout, solo se bypassa el data plane.",
      "Documentado en SUPABASE_JS_INCIDENT.md (en raiz del repo) con diagnostico, intentos fallidos, fix y como reconocer el bug si vuelve a aparecer.",
      "Anadido un build label fijo en la esquina arriba-derecha (timestamp) que se bumpea en cada commit, util para ver visualmente cuando Pages ha servido un deploy nuevo.",
      "Reducido el seed de movimientos demo a una sola entrada explicita ('Borra este movimiento') para que testers nuevos empiecen practicamente vacios.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "fdf2d79",
    title: "Fase 3 — paso 1: rename persona→contacto en todo el repo",
    changes: [
      "UI: pestaña \"Personas\" pasa a \"Contactos\". Labels, placeholders y mensajes actualizados (\"Selecciona contacto\", \"Sin contactos creados\", etc).",
      "Modos compartidos en el formulario reflejan el nuevo termino (\"Contacto pago, partes iguales\", etc).",
      "Refactor JS: state.people→state.contacts, personId→contactId, savePeople→saveContacts, getPersonName→getContactName, syncSharedPersonOptions→syncSharedContactOptions, etc. Renombrado features/people.js a features/contacts.js.",
      "Cloud: tabla `people` y columna `shared_entries.person_id` renombradas a `contacts` y `contact_id`. Schema actualizado y migracion idempotente en supabase/migrate-3-people-to-contacts.sql.",
      "LocalStorage: nueva clave `flowgrid.contacts.v1`. Migracion automatica desde la antigua `flowgrid.people.v1` en el primer boot tras la actualizacion (copia y borra la antigua).",
      "Backups: el formato exportado pasa a v3 con `contacts` y `contactId`. La importacion sigue aceptando backups v<3 con `people`/`personId` mapeandolos al vuelo.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "29281ea",
    title: "Fase 2 cerrada: backend cloud validado end-to-end",
    changes: [
      "Login con magic-link funcionando, persistencia de sesion correcta, hidratacion desde cloud OK, push de movimientos nuevos OK, logout OK.",
      "Validado en escritorio y movil. La app sigue siendo single-user; multiusuario llega en Fase 3.",
      "Limpieza: retirados los console.log diagnosticos que se anadieron para localizar el cuelgue del lock huerfano.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "67aff3b",
    title: "Fix: bootApp se colgaba en getSession por lock huerfano",
    changes: [
      "Tras arreglar el gate, el boot se quedaba en `[cloud hydrate] start` para siempre porque supabase.auth.getSession() esperaba un navigator.locks que estaba huerfano.",
      "Sustituido el lock por un no-op en la config de auth. La app es single-tab, no necesita sincronizacion entre tabs.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "86ce048",
    title: "Fix: el gate de auth tapaba la app booteada",
    changes: [
      "El CSS .auth-gate { display: grid } ganaba por especificidad al atributo hidden del HTML, asi que aunque hideAuthGate() seteara gate.hidden=true el formulario seguia visible sobre la app ya renderizada por z-index.",
      "Anadida regla .auth-gate[hidden] { display: none } que devuelve al atributo el control de la visibilidad.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "7f3c479",
    title: "Core estatico inicial",
    changes: [
      "App estatica preparada para GitHub Pages con navegacion por modulos.",
      "Core de movimientos con alta, listado, filtros, resumen y persistencia local.",
      "Panel de configuracion para conceptos y categorias, con edicion inline.",
      "Modulo Novedades conectado a changelog.js.",
      "Criterios globales de fecha en es-ES, formato DD/MM/AAAA y hora 24h.",
      "Selector de fecha propio con semanas empezando en lunes.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "main@HEAD",
    title: "Densidad y ajustes visuales",
    changes: [
      "Escala general reducida para aprovechar mejor el espacio disponible.",
      "Listado de movimientos convertido a filas tabulares de una sola linea.",
      "Corregida la alineacion entre cabeceras y contenido de movimientos.",
      "Columnas de movimientos reordenadas y acciones de editar/eliminar separadas.",
      "El borrado de movimientos solicita confirmacion.",
      "Iconos sustituidos por SVGs minimalistas inline.",
      "Paneles centrados en escritorio dentro del espacio disponible.",
      "Configuracion reorganizada en conceptos/categorias, importacion CSV y backup JS.",
      "Importacion CSV con previsualizacion y backup JS exportable/importable.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "dev@HEAD",
    title: "Analisis temporal y gastos compartidos",
    changes: [
      "Resumen retirado de Movimientos y creados modulos Mes a mes y Año a Año con desglose por concepto/categoria.",
      "Navegacion separada por bloques y primer modulo Compartidos aislado de movimientos/configuracion.",
      "Home reorganizado en grupos Dineritos/Sistema y separador lateral tras Home en la barra superior.",
      "Alta de movimientos movida a modal responsive y categoria derivada automaticamente del concepto.",
      "Bloque Gasto compartido en el formulario: con quien y parte que debe, solo activable en gastos.",
      "Los gastos compartidos generan deudas con estado pendiente/satisfecha visibles en Compartidos.",
      "Anadida columna Compartido en el listado de movimientos para identificar gastos con deuda asociada.",
      "Borrado directo de deudas desde Compartidos con confirmacion.",
      "Limpieza automatica de deudas compartidas al borrar el movimiento que las origina.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "dev@HEAD",
    title: "Tarjetas en movil y duplicar movimientos",
    changes: [
      "Home: retirados los titulos Dineritos/Sistema, sustituidos por una linea sutil entre grupos.",
      "Movimientos en movil renderizados como tarjetas agrupadas por fecha, manteniendo la fila tabular en escritorio.",
      "Cada tarjeta muestra concepto y nota arriba a la izquierda, importe centrado, recurrencia arriba a la derecha y compartido abajo a la izquierda.",
      "Nuevo boton Copiar en cada movimiento que abre el modal pre-rellenado para crear entradas similares.",
      "Calendario del selector de fecha por encima del modal (antes quedaba detras y era inusable).",
      "Cruz de cerrar el modal reposicionada en la esquina superior derecha del dialogo.",
      "Eliminado el placeholder Sin nota cuando un movimiento no tiene nota.",
    ],
  },
  {
    date: "2026-04-28",
    commit: "dev@HEAD",
    title: "Gastos compartidos rediseñados (modelo Splitwise)",
    changes: [
      "Personas como entidad propia: nueva pestaña Personas en Configuracion (CRUD por nombre).",
      "Calendario del selector de fecha 25% mas grande para mejor usabilidad en movil.",
      "Bloque Gasto compartido del modal con selector de persona (+ creacion inline) y 6 modos: tu pagaste / persona pago en partes iguales, desiguales o cantidad total.",
      "Modo desigual con dos importes propios y validacion en vivo: la suma debe coincidir con el total o sale aviso.",
      "Las partes iguales y total se calculan automaticamente; en partes desiguales hay que introducir cada parte manualmente.",
      "Cuando alguien te debe la cantidad total no se crea movimiento personal (es prestamo puro), solo entrada en Compartidos.",
      "En el resto de modos el movimiento personal refleja solo tu parte (como si la otra persona ya hubiera pagado la suya).",
      "Panel Compartidos rediseñado: tarjetas de saldo por persona (te debe / le debes), filtro por persona y tabs Pendientes / Archivo.",
      "Pago a cuenta: nuevo modal para registrar pagos parciales que reducen el saldo sin cerrarlo.",
      "Liquidar saldo: cierra todas las pendientes con esa persona y crea entrada de liquidacion en el archivo.",
      "Archivo de Compartidos: las liquidaciones agrupan las entradas cerradas con titulo, fecha e importe liquidado.",
      "Persona solo se puede borrar si no tiene entradas; movimiento con shared liquidado no se puede borrar (integridad de archivo).",
      "Modelo de datos limpio (start clean): claves nuevas flowgrid.people.v1 y flowgrid.shared.v2; los datos de la version anterior dejan de cargarse.",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Compartidos: acciones por persona y mejor rendimiento",
    changes: [
      "Botones Registrar pago y Liquidar saldo movidos al interior de cada tarjeta de saldo (antes solo aparecian al filtrar por una persona, costaba descubrirlos).",
      "Cada accion lleva un subtitulo aclaratorio: Registrar pago reduce el saldo sin cerrar entradas (pago a cuenta); Liquidar saldo cierra todas las pendientes con esa persona y las archiva.",
      "Nuevo boton Ver entradas en la tarjeta para saltar al listado filtrado por esa persona.",
      "Render quirurgico: las acciones ya no rebuilcen toda la app (movimientos+analisis+compartidos+conceptos+categorias+changelog) en cada interaccion. Solo se actualiza lo afectado por cada cambio.",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Compartidos simplificado, edicion y separadores de mes",
    changes: [
      "Modelo simplificado: olvidamos el archivo y las pestañas Pendientes/Archivo. Toda liquidacion se registra como una entrada de tipo pago que afecta al saldo. Una sola lista por persona.",
      "Un unico boton Liquidar saldo en cada tarjeta. Abre modal con importe pre-rellenado al saldo y direccion inferida (paga quien debe).",
      "Edicion de entradas compartidas: nuevo boton Editar en cada entrada de gasto. Reabre el modal de movimiento con el bloque shared pre-rellenado (persona, modo, partes).",
      "La edicion mantiene la coherencia movimiento ↔ entrada compartida: al guardar se borran los registros antiguos y se recrean con los datos nuevos. Si cambias el modo (ej. de partes iguales a se te debe total), se ajusta automaticamente si hay movimiento o no.",
      "Tambien al editar un movimiento desde Movimientos: si tenia entrada compartida asociada, el bloque shared aparece pre-rellenado y los cambios afectan a ambas piezas.",
      "Separador de mes en el listado de Movimientos y de Compartidos. En Movimientos se mantiene ademas el separador diario en movil.",
      "Las entradas de tipo pago se distinguen visualmente (fondo azul claro).",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Refactor a ES modules (sin cambios funcionales)",
    changes: [
      "app.js dividido en 16 modulos por dominio (constants, utils, state, dom, storage, people, movements, shared, analysis, datepicker, settings, csv, backup, changelog-view, render, app).",
      "El entry app.js queda como wiring minimo: initState, setInitialDate, render y listeners globales.",
      "Estado mutable global centralizado en un objeto state singleton; mutaciones in-place desde cada modulo.",
      "Cada modulo registra sus propios listeners; render.js coordina el repintado completo.",
      "index.html carga app.js como type=\"module\". changelog.js (datos) y styles.css sin cambios.",
      "Sin cambios de comportamiento: misma funcionalidad, mismas claves de localStorage, mismas vistas.",
      "Preparacion para la Fase 2 (mover storage a Supabase) y la Fase 3 (cuentas e invitaciones).",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Modulos organizados en carpetas (core/features/ui)",
    changes: [
      "Los 15 modulos pasan de la raiz a tres carpetas por responsabilidad: core/ (state, dom, storage, utils, constants), features/ (movements, shared, people, analysis, settings, csv, backup) y ui/ (datepicker, render, changelog-view).",
      "El entry app.js sigue en la raiz; index.html no necesita cambios porque solo apunta a app.js.",
      "Imports relativos actualizados con extension .js explicita (requisito de los ES modules en el navegador).",
      "Sin cambios funcionales: misma app, misma persistencia, mismas vistas. Validado en Edge headless contra el servidor local.",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Emisor/receptor admite vacio",
    changes: [
      "Dejar el campo emisor/receptor vacio ya no muestra 'Sin emisor': la celda queda en blanco.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "dev@HEAD",
    title: "Bootstrap de la app por onAuthChange (sin race con getSession)",
    changes: [
      "app.js antes hacia await getSession() y, si era null, mostraba el gate. En algunos casos getSession devolvia null aun habiendose creado la sesion (timing race con la inicializacion async de supabase-js), asi que el gate se quedaba arriba aunque el log mostrase SIGNED_IN.",
      "Ahora app.js solo escucha onAuthChange, que dispara INITIAL_SESSION en cuanto el listener se registra (ya este la inicializacion terminada o no) y SIGNED_IN/SIGNED_OUT en cada cambio. Una unica fuente de verdad, sin race.",
      "Logs anyadidos: [app] booting, [app] boot complete y [app] auth change: ... para diagnosticar el flujo del login en consola si vuelve a fallar.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "dev@HEAD",
    title: "Captura de URL inicial para diagnostico de auth",
    changes: [
      "Snippet inline en index.html que guarda window.location.href en window.__FG_INITIAL_URL__ antes de que se cargue ningun modulo.",
      "Si el redirect del magic link traia access_token o code y aun asi acabas en el gate, ahora se ve un mensaje explicito en el feedback en vez de quedarse mudo.",
      "El warning va tambien a consola con la URL completa, util para diagnosticar configuraciones mal puestas en Supabase.",
    ],
  },
  {
    date: "2026-04-30",
    commit: "dev@HEAD",
    title: "Auth con flow implicit y errores visibles",
    changes: [
      "Magic link cambiado a flowType implicit (token en el #hash, no requiere abrir el enlace en el mismo navegador donde se rellena el email).",
      "Si el redirect llega con error_description o error en la URL, se muestra en el feedback del gate en vez de quedar mudo.",
      "Eventos de auth (sign-in, sign-out, refresh) logueados en consola con prefijo [supabase auth] para depuracion.",
    ],
  },
  {
    date: "2026-04-29",
    commit: "dev@HEAD",
    title: "Backend en la nube (Supabase) - Fase 2",
    changes: [
      "FlowGrid pasa de localStorage puro a backend cloud: Supabase Postgres con Row Level Security.",
      "Login por magic link: introduces tu email una vez, te llega un enlace, entras sin contrasenas. La sesion persiste entre dispositivos.",
      "Schema con cuatro tablas (movements, settings, people, shared_entries) y politicas RLS owner_id = auth.uid() en todas. Ver supabase/schema.sql.",
      "Sync local-first: localStorage sigue siendo la fuente rapida del UI. Tras cada save se hace push de fondo a Supabase (delete extras + upsert) sin bloquear.",
      "Hidratacion al arrancar: cloud manda. Si el cloud esta vacio (primer login en una cuenta) sube tu localStorage como semilla -> migracion automatica.",
      "Gate de auth: si no hay sesion, ves el formulario de login y nada mas; si la hay, app normal con tu email y boton de logout en la sidebar.",
      "Tres modulos nuevos: core/config.js (URL+anon key publica), core/supabase.js (cliente+auth), core/cloud.js (push y hydrate con field mapping camelCase<->snake_case).",
      "Forkeable: alguien que clone el repo solo tiene que cambiar los dos valores de core/config.js para apuntar a su propio Supabase.",
    ],
  },
];
